# 🐳 Docker Compose para Stack21 - Deploy Privado
# ===============================================

version: '3.8'

services:
  # Aplicación Stack21
  app:
    build: .
    container_name: stack21-app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DATABASE_URL=postgresql://stack21:password@db:5432/stack21_prod
      - NEXTAUTH_URL=http://localhost:3000
      - NEXTAUTH_SECRET=your-secret-here
      - OPENAI_API_KEY=your-openai-key
    depends_on:
      - db
    restart: unless-stopped
    networks:
      - stack21-network
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Base de datos PostgreSQL
  db:
    image: postgres:15-alpine
    container_name: stack21-db
    environment:
      POSTGRES_DB: stack21_prod
      POSTGRES_USER: stack21
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --lc-collate=C --lc-ctype=C"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backups:/backups
    ports:
      - "5432:5432"
    restart: unless-stopped
    networks:
      - stack21-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U stack21 -d stack21_prod"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis para cache (opcional)
  redis:
    image: redis:7-alpine
    container_name: stack21-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    networks:
      - stack21-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 3s
      retries: 3

  # Nginx como reverse proxy (opcional)
  nginx:
    image: nginx:alpine
    container_name: stack21-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    restart: unless-stopped
    networks:
      - stack21-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local

networks:
  stack21-network:
    driver: bridge